name: frenly_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  pretty_dio_logger: ^1.4.0
  shared_preferences:
  google_fonts: ^6.2.1
  dio: ^5.7.0
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  flutter_widget_from_html_core: ^0.15.2
  awesome_bottom_bar: ^1.2.4
  feather_icons: ^1.2.0
  animation_wrappers: ^3.0.0
  flutter_svg: ^2.0.17
  hexcolor: ^3.0.1
  cupertino_onboarding:
  fluttertoast: ^8.2.10
  flutter_staggered_grid_view: ^0.7.0
  flutter_masonry_view: ^0.0.2
  floating_frosted_bottom_bar:
  spincircle_bottom_bar:
  curved_navigation_bar: ^1.0.6
  modal_progress_hud_nsn: ^0.5.1
  get: ^4.6.6
  dynamic_height_grid_view: ^0.0.4
  permission_handler: ^11.3.1
  flutter_image_compress :
  circular_menu: ^4.0.0
  chewie: ^1.9.2
  image_picker: ^1.1.2
  image_cropper: ^8.1.0
  video_player: ^2.9.2
  camera:
  path_provider:
  path:
  socket_io_client: ^3.0.2
  flutter_local_notifications:
  timeago: ^3.7.0
  flick_video_player: ^0.9.0
  flutter_translate: ^4.0.0


  #  firebase
  firebase_messaging: ^15.2.0
  firebase_analytics: ^11.4.0
  firebase_core: ^3.10.0

  flutter_riverpod: ^2.4.0

  intl:
  connectivity_plus:
  win32: ^5.10.0
#  uni_links3: ^0.5.1
#  uni_links: ^0.5.1

  app_links: ^6.4.1
  video_compress: ^3.1.4
  video_editor: ^3.0.0
  textfield_tags: ^3.0.1
  detectable_text_field: ^3.0.2
  url_launcher: ^6.1.14
  device_info_plus:
  pinch_zoom: ^2.0.1
  insta_image_viewer: ^1.0.4
  photo_view: ^0.15.0


  velocity_x:
    git:
      url: https://github.com/iampawan/VelocityX.git
      ref: stable

dependency_overrides:
  video_thumbnail:
    git: https://github.com/Shahidbangash/video_thumbnail.git

  intl: ^0.20.2

  flutter_localizations:
    sdk: flutter

#  flutter_translate:
#    git:
#      url: git@github.com:tonkasl/flutter_translate.git



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2

flutter_locales:
  git:
    url: https://github.com/tonkasl/flutter_locales.git
    ref: master


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/image/
    - assets/fonts/
    - assets/icons/
    - assets/logo/

  # An image asset can refer to oneor more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tenor Sans
      fonts:
        - asset: assets/fonts/TenorSans.ttf
          weight: 400

    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterLight.ttf
          weight: 300
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500

    - family: Vujahday Script
      fonts:
        - asset: assets/fonts/VujahdayScriptRegular.ttf
          weight: 400
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
